INSERT INTO FOOD (ID, NAME) VALUES
(1, 'Dog'),
(2, 'Pizza'),
(3, 'Hamburger');

INSERT INTO PERSON (NAME) VALUES
('David');

INSERT INTO RECORDS (PERSON_ID, FOOD_ID, COUNT_EATEN, TIME_MINUTES) VALUES
(1, 1, 44, 3),
(1, 1, 21, 3),
(1, 1, 55, 3),
(1, 1, 13, 3);
