CREATE TABLE FOOD (
	ID INT PRIMARY KEY,
	NAME VARCHAR(50)
);

CREATE TABLE PERSON (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(80)
);

CREATE TABLE RECORDS (
	ID SERIAL PRIMARY KEY,
	PERSON_ID INT REFERENCES PERSON(ID),
	FOOD_ID INT REFERENCES FOOD(ID),
	COUNT_EATEN INT,
	TIME_MINUTES INT
);